package constants

// Config values read from OS environment
const (
	DEPLOY_ENV_KEY           = "DEPLOY_ENV"
	APP_CONFIG_PATH_ENV_KEY  = "APP_CONFIG_PATH"
	MEMPHIS_HOST_ENV_KEY     = "MEMPHIS_HOST"
	MEMPHIS_USERNAME_ENV_KEY = "MEMPHIS_USERNAME"
	MEMPHIS_TOKEN_ENV_KEY    = "MEMPHIS_TOKEN"
	MEMPHIS_PORT_ENV_KEY     = "MEMPHIS_PORT"
	SOURCE_OF_NEWS_ENV_KEY   = "SOURCE_OF_NEWS"
	SCRAPE_INTERVAL_ENV_KEY  = "SCRAPE_INTERVAL"
	STATION_NEWS_ID_ENV_KEY  = "STATION_NEWS_ID"
	GUARDIAN_API_KEY_ENV_KEY = "GUARDIAN_API_KEY"
)

// - SOURCE_OF_NEWS = THEGUARDIAN # e.g THEGUARDIAN, NEWSAPI
var ALL_CONFIG_ENV_KEYS = [...]string{
	DEPLOY_ENV_KEY,
	APP_CONFIG_PATH_ENV_KEY,
	MEMPHIS_HOST_ENV_KEY,
	MEMPHIS_USERNAME_ENV_KEY,
	MEMPHIS_TOKEN_ENV_KEY,
	MEMPHIS_PORT_ENV_KEY,
	SOURCE_OF_NEWS_ENV_KEY,
	SCRAPE_INTERVAL_ENV_KEY,
	STATION_NEWS_ID_ENV_KEY,
	GUARDIAN_API_KEY_ENV_KEY,
}
